use playyn;

insert into track values ("1", "1", "Donna", "2019-05-05", "1", "4.99", "183000", True, "https://upload.wikimedia.org/wikipedia/en/5/54/The_Lumineers_-_III.png");
insert into track values ("2", "2", "Life In The City", "2019-05-06", "1", "4.99", "210600", True, "https://upload.wikimedia.org/wikipedia/en/5/54/The_Lumineers_-_III.png");
insert into track values ("3", "3", "Gloria", "2019-05-07", "1", "4.99", "201600", True, "https://upload.wikimedia.org/wikipedia/en/5/54/The_Lumineers_-_III.png");
insert into track values ("4", "4", "It Wasn't Easy To Be Happy For You", "2019-05-08", "1", "4.99", "200400", True, "https://upload.wikimedia.org/wikipedia/en/5/54/The_Lumineers_-_III.png");
insert into track values ("5", "5", "Leader Of The Landslide", "2019-05-09", "1", "4.99", "332400", True, "https://upload.wikimedia.org/wikipedia/en/5/54/The_Lumineers_-_III.png");
insert into track values ("6", "6", "Left For Denver", "2019-05-10", "1", "4.99", "189600", True, "https://upload.wikimedia.org/wikipedia/en/5/54/The_Lumineers_-_III.png");
insert into track values ("7", "7", "My Cell", "2019-05-11", "1", "4.99", "189600", True, "https://upload.wikimedia.org/wikipedia/en/5/54/The_Lumineers_-_III.png");
insert into track values ("8", "8", "Jimmy Sparks", "2019-05-12", "1", "4.99", "333000", True, "https://upload.wikimedia.org/wikipedia/en/5/54/The_Lumineers_-_III.png");
insert into track values ("9", "9", "April", "2019-05-13", "1", "4.99", "30000", True, "https://upload.wikimedia.org/wikipedia/en/5/54/The_Lumineers_-_III.png");
insert into track values ("10", "10", "Salt And The Sea", "2019-05-14", "1", "4.99", "258000", True, "https://upload.wikimedia.org/wikipedia/en/5/54/The_Lumineers_-_III.png");

insert into audio_features values ("1", "0.60", "0.72", "0.78", "0.63", "0.25", "0.56", "0.91", "0.34", "0.72", "0.51", "0.34");
insert into audio_features values ("2", "0.56", "0.55", "0.17", "0.65", "0.22", "0.94", "0.88", "1.00", "0.20", "0.22", "0.23");
insert into audio_features values ("3", "0.72", "0.45", "0.42", "0.83", "1.00", "0.83", "0.98", "0.91", "0.38", "0.28", "0.11");
insert into audio_features values ("4", "0.75", "0.48", "0.27", "0.36", "0.27", "0.51", "0.73", "0.77", "0.39", "0.26", "0.19");
insert into audio_features values ("5", "0.46", "0.41", "0.34", "0.25", "0.73", "0.39", "0.66", "0.44", "0.73", "0.37", "0.73");
insert into audio_features values ("6", "0.86", "0.70", "0.58", "0.35", "1.00", "0.44", "0.88", "0.67", "0.98", "0.64", "0.27");
insert into audio_features values ("7", "0.15", "0.57", "0.83", "0.42", "0.84", "0.82", "0.64", "0.80", "0.82", "0.82", "0.47");
insert into audio_features values ("8", "0.81", "0.86", "0.50", "0.60", "0.23", "0.41", "0.65", "0.69", "0.80", "0.16", "0.56");
insert into audio_features values ("9", "0.99", "0.10", "0.37", "0.33", "0.87", "0.26", "0.44", "0.53", "0.56", "0.99", "0.82");
insert into audio_features values ("10", "0.84", "0.37", "0.65", "0.60", "0.46", "0.65", "0.24", "0.70", "0.45", "0.70", "0.18");

insert into album values ("1", "III", "2019-05-15", "https://upload.wikimedia.org/wikipedia/en/5/54/The_Lumineers_-_III.png");

insert into album_track values ("1", "1");
insert into album_track values ("1", "2");
insert into album_track values ("1", "3");
insert into album_track values ("1", "4");
insert into album_track values ("1", "5");
insert into album_track values ("1", "6");
insert into album_track values ("1", "7");
insert into album_track values ("1", "8");
insert into album_track values ("1", "9");
insert into album_track values ("1", "10");

insert into genre values ("1", "Rock");
insert into genre values ("2", "Pop music");
insert into genre values ("3", "Popular music");
insert into genre values ("4", "Hip hop music");
insert into genre values ("5", "Rhythm and blues");
insert into genre values ("6", "Country music");
insert into genre values ("7", "Folk music");
insert into genre values ("8", "Jazz");
insert into genre values ("9", "Classical music");
insert into genre values ("10", "Blues");
insert into genre values ("11", "Electronic music");
insert into genre values ("12", "Musical theatre");
insert into genre values ("13", "Heavy metal");
insert into genre values ("14", "Electronic dance music");
insert into genre values ("15", "Punk rock");
insert into genre values ("16", "Alternative rock");
insert into genre values ("17", "Dance music");
insert into genre values ("18", "World music");
insert into genre values ("19", "Soul music");
insert into genre values ("20", "Music of the United States");
insert into genre values ("21", "Funk");
insert into genre values ("22", "Indie rock");
insert into genre values ("23", "Singing");
insert into genre values ("24", "Pop rock");
insert into genre values ("25", "Reggae");
insert into genre values ("26", "Techno");
insert into genre values ("27", "Latin music");
insert into genre values ("28", "Contemporary R&amp;B");
insert into genre values ("29", "House music");
insert into genre values ("30", "Dubstep");
insert into genre values ("31", "Easy listening");
insert into genre values ("32", "New-age music");
insert into genre values ("33", "Rapping");
insert into genre values ("34", "Rock and roll");
insert into genre values ("35", "Experimental music");
insert into genre values ("36", "New wave");
insert into genre values ("37", "Instrumental");
insert into genre values ("38", "Disco");
insert into genre values ("39", "Music of Latin America");
insert into genre values ("40", "Electronica");
insert into genre values ("41", "Jazz fusion");
insert into genre values ("42", "Ambient music");
insert into genre values ("43", "Musical");
insert into genre values ("44", "Ska");
insert into genre values ("45", "Progressive rock");
insert into genre values ("46", "Hardcore punk");
insert into genre values ("47", "Bluegrass");
insert into genre values ("48", "Art music");
insert into genre values ("49", "Electro");
insert into genre values ("50", "Gospel music");
insert into genre values ("51", "Soundtrack");

insert into track_genre values ("1", "6");
insert into track_genre values ("1", "7");
insert into track_genre values ("2", "6");
insert into track_genre values ("2", "7");
insert into track_genre values ("3", "6");
insert into track_genre values ("3", "7");
insert into track_genre values ("3", "10");
insert into track_genre values ("4", "6");
insert into track_genre values ("4", "7");
insert into track_genre values ("5", "6");
insert into track_genre values ("5", "7");
insert into track_genre values ("6", "6");
insert into track_genre values ("6", "7");
insert into track_genre values ("7", "6");
insert into track_genre values ("7", "7");
insert into track_genre values ("8", "6");
insert into track_genre values ("8", "7");
insert into track_genre values ("9", "6");
insert into track_genre values ("9", "7");
insert into track_genre values ("9", "37");
insert into track_genre values ("10", "6");
insert into track_genre values ("10", "7");

insert into available_market values ("1", "US", "United States");
insert into available_market values ("2", "UK", "United Kingdom");
insert into available_market values ("3", "IN", "India");

insert into track_market values ("1", "1");
insert into track_market values ("1", "2");
insert into track_market values ("1", "3");
insert into track_market values ("2", "1");
insert into track_market values ("2", "2");
insert into track_market values ("2", "3");
insert into track_market values ("3", "1");
insert into track_market values ("3", "2");
insert into track_market values ("3", "3");
insert into track_market values ("4", "1");
insert into track_market values ("4", "2");
insert into track_market values ("4", "3");
insert into track_market values ("5", "1");
insert into track_market values ("5", "2");
insert into track_market values ("5", "3");
insert into track_market values ("6", "1");
insert into track_market values ("6", "2");
insert into track_market values ("6", "3");
insert into track_market values ("7", "1");
insert into track_market values ("7", "2");
insert into track_market values ("7", "3");
insert into track_market values ("8", "1");
insert into track_market values ("8", "2");
insert into track_market values ("8", "3");
insert into track_market values ("9", "1");
insert into track_market values ("9", "2");
insert into track_market values ("9", "3");
insert into track_market values ("10", "1");
insert into track_market values ("10", "2");
insert into track_market values ("10", "3");

insert into album_market values ("1", "1");
insert into album_market values ("1", "2");
insert into album_market values ("1", "3");

insert into address values("1", "7 Middlefield Road", "2", "Redwood City", "CA", "US", "94063");
insert into address values("2", "12 Second Avenue", "4", "San Mateo", "CA", "US", "94401");
insert into address values("3", "24 Middle Avenue", "5", "Menlo Park", "CA", "US", "94025");
insert into address values("4", "4 Arbor Road", "7", "Menlo Park", "CA", "US", "94025");
insert into address values("5", "45 Middle Avenue", "8", "Menlo Park", "CA", "US", "94025");
insert into address values("6", "7 Middlefield Road", "9", "Redwood City", "CA", "US", "94063");
insert into address values("7", "9 Middlefield Road", "8", "Redwood City", "CA", "US", "94063");
insert into address values("8", "2 Euclid Avenue.", "34", "Redwood City", "CA", "US", "94061");
insert into address values("9", "456 Middlefield Road", "2nd Floor", "Redwood City", "CA", "US", "94063");
insert into address values("10", "32 Marine Parkway.", "4", "Redwood City", "CA", "US", "94065");
insert into address values("11", "1 Veterans Blvd.", "2", "Redwood City", "CA", "US", "94063");
insert into address values("12", "23 Valencia Street", "1", "San Francisco", "CA", "US", "94110");
insert into address values("13", "5 South Bernardo", "6", "Sunnyvale", "CA", "US", "94087");
insert into address values("14", "7 South Spruce Avenue", "2", "South San Francisco", "CA", "US", "94080");
insert into address values("15", "12 Fifth Avenue", "2", "Redwood City", "CA", "US", "94063");
insert into address values("16", "12 West 39th Avenue", "3", "San Mateo", "CA", "US", "94403");
insert into address values("17", "67 El Camino Real", "1", "Belmont", "CA", "US", "94002");
insert into address values("18", "8 Avenue of the fellows", "Suite 100", "San Francisco", "CA", "US", "94103");

insert into country_code values("Afghanistan", "93");
insert into country_code values("Albania", "355");
insert into country_code values("Algeria", "213");
insert into country_code values("American Samoa", "1684");
insert into country_code values("Andorra", "376");
insert into country_code values("Angola", "244");
insert into country_code values("Anguilla", "1264");
insert into country_code values("Antarctica", "672");
insert into country_code values("Antigua and Barbuda", "1268");
insert into country_code values("Argentina", "54");
insert into country_code values("Armenia", "374");
insert into country_code values("Aruba", "297");
insert into country_code values("Australia", "61");
insert into country_code values("Austria", "43");
insert into country_code values("Azerbaijan", "994");
insert into country_code values("Bahamas", "1242");
insert into country_code values("Bahrain", "973");
insert into country_code values("Bangladesh", "880");
insert into country_code values("Barbados", "1246");
insert into country_code values("Belarus", "375");
insert into country_code values("Belgium", "32");
insert into country_code values("Belize", "501");
insert into country_code values("Benin", "229");
insert into country_code values("Bermuda", "1441");
insert into country_code values("Bhutan", "975");
insert into country_code values("Bolivia", "591");
insert into country_code values("Bosnia and Herzegovina", "387");
insert into country_code values("Botswana", "267");
insert into country_code values("Brazil", "55");
insert into country_code values("British Indian Ocean Territory", "246");
insert into country_code values("British Virgin Islands", "1284");
insert into country_code values("Brunei", "673");
insert into country_code values("Bulgaria", "359");
insert into country_code values("Burkina Faso", "226");
insert into country_code values("Burundi", "257");
insert into country_code values("Cambodia", "855");
insert into country_code values("Cameroon", "237");
insert into country_code values("Canada", "1");
insert into country_code values("Cape Verde", "238");
insert into country_code values("Cayman Islands", "1345");
insert into country_code values("Central African Republic", "236");
insert into country_code values("Chad", "235");
insert into country_code values("Chile", "56");
insert into country_code values("China", "86");
insert into country_code values("Christmas Island", "61");
insert into country_code values("Cocos Islands", "61");
insert into country_code values("Colombia", "57");
insert into country_code values("Comoros", "269");
insert into country_code values("Cook Islands", "682");
insert into country_code values("Costa Rica", "506");
insert into country_code values("Croatia", "385");
insert into country_code values("Cuba", "53");
insert into country_code values("Curacao", "599");
insert into country_code values("Cyprus", "357");
insert into country_code values("Czech Republic", "420");
insert into country_code values("Democratic Republic of the Congo", "243");
insert into country_code values("Denmark", "45");
insert into country_code values("Djibouti", "253");
insert into country_code values("Dominica", "1767");
insert into country_code values("Dominican Republic", "1809");
insert into country_code values("East Timor", "670");
insert into country_code values("Ecuador", "593");
insert into country_code values("Egypt", "20");
insert into country_code values("El Salvador", "503");
insert into country_code values("Equatorial Guinea", "240");
insert into country_code values("Eritrea", "291");
insert into country_code values("Estonia", "372");
insert into country_code values("Ethiopia", "251");
insert into country_code values("Falkland Islands", "500");
insert into country_code values("Faroe Islands", "298");
insert into country_code values("Fiji", "679");
insert into country_code values("Finland", "358");
insert into country_code values("France", "33");
insert into country_code values("French Polynesia", "689");
insert into country_code values("Gabon", "241");
insert into country_code values("Gambia", "220");
insert into country_code values("Georgia", "995");
insert into country_code values("Germany", "49");
insert into country_code values("Ghana", "233");
insert into country_code values("Gibraltar", "350");
insert into country_code values("Greece", "30");
insert into country_code values("Greenland", "299");
insert into country_code values("Grenada", "1473");
insert into country_code values("Guam", "1671");
insert into country_code values("Guatemala", "502");
insert into country_code values("Guernsey", "441481");
insert into country_code values("Guinea", "224");
insert into country_code values("Guinea-Bissau", "245");
insert into country_code values("Guyana", "592");
insert into country_code values("Haiti", "509");
insert into country_code values("Honduras", "504");
insert into country_code values("Hong Kong", "852");
insert into country_code values("Hungary", "36");
insert into country_code values("Iceland", "354");
insert into country_code values("India", "91");
insert into country_code values("Indonesia", "62");
insert into country_code values("Iran", "98");
insert into country_code values("Iraq", "964");
insert into country_code values("Ireland", "353");
insert into country_code values("Isle of Man", "441624");
insert into country_code values("Israel", "972");
insert into country_code values("Italy", "39");
insert into country_code values("Ivory Coast", "225");
insert into country_code values("Jamaica", "1876");
insert into country_code values("Japan", "81");
insert into country_code values("Jersey", "441534");
insert into country_code values("Jordan", "962");
insert into country_code values("Kazakhstan", "7");
insert into country_code values("Kenya", "254");
insert into country_code values("Kiribati", "686");
insert into country_code values("Kosovo", "383");
insert into country_code values("Kuwait", "965");
insert into country_code values("Kyrgyzstan", "996");
insert into country_code values("Laos", "856");
insert into country_code values("Latvia", "371");
insert into country_code values("Lebanon", "961");
insert into country_code values("Lesotho", "266");
insert into country_code values("Liberia", "231");
insert into country_code values("Libya", "218");
insert into country_code values("Liechtenstein", "423");
insert into country_code values("Lithuania", "370");
insert into country_code values("Luxembourg", "352");
insert into country_code values("Macau", "853");
insert into country_code values("Macedonia", "389");
insert into country_code values("Madagascar", "261");
insert into country_code values("Malawi", "265");
insert into country_code values("Malaysia", "60");
insert into country_code values("Maldives", "960");
insert into country_code values("Mali", "223");
insert into country_code values("Malta", "356");
insert into country_code values("Marshall Islands", "692");
insert into country_code values("Mauritania", "222");
insert into country_code values("Mauritius", "230");
insert into country_code values("Mayotte", "262");
insert into country_code values("Mexico", "52");
insert into country_code values("Micronesia", "691");
insert into country_code values("Moldova", "373");
insert into country_code values("Monaco", "377");
insert into country_code values("Mongolia", "976");
insert into country_code values("Montenegro", "382");
insert into country_code values("Montserrat", "1664");
insert into country_code values("Morocco", "212");
insert into country_code values("Mozambique", "258");
insert into country_code values("Myanmar", "95");
insert into country_code values("Namibia", "264");
insert into country_code values("Nauru", "674");
insert into country_code values("Nepal", "977");
insert into country_code values("Netherlands", "31");
insert into country_code values("Netherlands Antilles", "599");
insert into country_code values("New Caledonia", "687");
insert into country_code values("New Zealand", "64");
insert into country_code values("Nicaragua", "505");
insert into country_code values("Niger", "227");
insert into country_code values("Nigeria", "234");
insert into country_code values("Niue", "683");
insert into country_code values("North Korea", "850");
insert into country_code values("Northern Mariana Islands", "1670");
insert into country_code values("Norway", "47");
insert into country_code values("Oman", "968");
insert into country_code values("Pakistan", "92");
insert into country_code values("Palau", "680");
insert into country_code values("Palestine", "970");
insert into country_code values("Panama", "507");
insert into country_code values("Papua New Guinea", "675");
insert into country_code values("Paraguay", "595");
insert into country_code values("Peru", "51");
insert into country_code values("Philippines", "63");
insert into country_code values("Pitcairn", "64");
insert into country_code values("Poland", "48");
insert into country_code values("Portugal", "351");
insert into country_code values("Puerto Rico", "1787");
insert into country_code values("Qatar", "974");
insert into country_code values("Republic of the Congo", "242");
insert into country_code values("Reunion", "262");
insert into country_code values("Romania", "40");
insert into country_code values("Russia", "7");
insert into country_code values("Rwanda", "250");
insert into country_code values("Saint Barthelemy", "590");
insert into country_code values("Saint Helena", "290");
insert into country_code values("Saint Kitts and Nevis", "1869");
insert into country_code values("Saint Lucia", "1758");
insert into country_code values("Saint Martin", "590");
insert into country_code values("Saint Pierre and Miquelon", "508");
insert into country_code values("Saint Vincent and the Grenadines", "1784");
insert into country_code values("Samoa", "685");
insert into country_code values("San Marino", "378");
insert into country_code values("Sao Tome and Principe", "239");
insert into country_code values("Saudi Arabia", "966");
insert into country_code values("Senegal", "221");
insert into country_code values("Serbia", "381");
insert into country_code values("Seychelles", "248");
insert into country_code values("Sierra Leone", "232");
insert into country_code values("Singapore", "65");
insert into country_code values("Sint Maarten", "1721");
insert into country_code values("Slovakia", "421");
insert into country_code values("Slovenia", "386");
insert into country_code values("Solomon Islands", "677");
insert into country_code values("Somalia", "252");
insert into country_code values("South Africa", "27");
insert into country_code values("South Korea", "82");
insert into country_code values("South Sudan", "211");
insert into country_code values("Spain", "34");
insert into country_code values("Sri Lanka", "94");
insert into country_code values("Sudan", "249");
insert into country_code values("Suriname", "597");
insert into country_code values("Svalbard and Jan Mayen", "47");
insert into country_code values("Swaziland", "268");
insert into country_code values("Sweden", "46");
insert into country_code values("Switzerland", "41");
insert into country_code values("Syria", "963");
insert into country_code values("Taiwan", "886");
insert into country_code values("Tajikistan", "992");
insert into country_code values("Tanzania", "255");
insert into country_code values("Thailand", "66");
insert into country_code values("Togo", "228");
insert into country_code values("Tokelau", "690");
insert into country_code values("Tonga", "676");
insert into country_code values("Trinidad and Tobago", "1868");
insert into country_code values("Tunisia", "216");
insert into country_code values("Turkey", "90");
insert into country_code values("Turkmenistan", "993");
insert into country_code values("Turks and Caicos Islands", "1649");
insert into country_code values("Tuvalu", "688");
insert into country_code values("U.S. Virgin Islands", "1340");
insert into country_code values("Uganda", "256");
insert into country_code values("Ukraine", "380");
insert into country_code values("United Arab Emirates", "971");
insert into country_code values("United Kingdom", "44");
insert into country_code values("United States", "1");
insert into country_code values("Uruguay", "598");
insert into country_code values("Uzbekistan", "998");
insert into country_code values("Vanuatu", "678");
insert into country_code values("Vatican", "379");
insert into country_code values("Venezuela", "58");
insert into country_code values("Vietnam", "84");
insert into country_code values("Wallis and Futuna", "681");
insert into country_code values("Western Sahara", "212");
insert into country_code values("Yemen", "967");
insert into country_code values("Zambia", "260");
insert into country_code values("Zimbabwe", "263");

insert into languages values ("1", "English");
insert into languages values ("2", "Spanish");

insert into artist values ("1", "Wesley", "Schultz", "Male", "1982-12-30", "1", "+16458619589", "thelumineers", "schultz.we@thelumineers.com");
insert into artist values ("2", "Neyla", "Pekarek", "Female", "1986-09-04", "11", "+13679541244", "thelumineers", "pekarek.ne@thelumineers.com");
insert into artist values ("3", "Fraites", "Jeremiah", "Male", "1986-01-17", "5", "+16985478965", "thelumineers", "jeremiah.fr@thelumineers.com");
insert into artist values ("4", "Maxwell", "Hughes", "Male", "1984-02-04", "7", "+13465798412", "thelumineers", "hughes.ma@thelumineers.com");
insert into artist values ("5", "Ben", "Wahamaki", "Male", "1988-05-06", "6", "+12134659787", "thelumineers", "wahamaki.ben@thelumineers.com");

insert into proficiency values ("1", "Vocal");
insert into proficiency values ("2", "Acoustic Guitar");
insert into proficiency values ("3", "Electric Guitar");
insert into proficiency values ("4", "Bass Guitar");
insert into proficiency values ("5", "Piano");
insert into proficiency values ("6", "Chello");
insert into proficiency values ("7", "Violin");
insert into proficiency values ("8", "Drums");
insert into proficiency values ("9", "Flute");

insert into artist_proficiency values ("1", "1");
insert into artist_proficiency values ("1", "5");
insert into artist_proficiency values ("2", "6");
insert into artist_proficiency values ("3", "1");
insert into artist_proficiency values ("3", "8");
insert into artist_proficiency values ("4", "2");
insert into artist_proficiency values ("5", "4");

insert into band values ("1", "The Lumineers");

insert into band_artist values ("1", "1");
insert into band_artist values ("1", "2");
insert into band_artist values ("1", "3");
insert into band_artist values ("1", "4");
insert into band_artist values ("1", "5");

insert into track_band values ("1", "1");
insert into track_band values ("2", "1");
insert into track_band values ("3", "1");
insert into track_band values ("4", "1");
insert into track_band values ("5", "1");
insert into track_band values ("6", "1");
insert into track_band values ("7", "1");
insert into track_band values ("8", "1");
insert into track_band values ("9", "1");
insert into track_band values ("10", "1");

insert into album_band values ("1", "1");